import algosdk from "algosdk";
import { env } from "./config.js";
import { getAlgorandClient } from "./algorand.js";
import { createOscorpSchema, updateOscorpPolicySchema } from "./schemas.js";

type CreateOscorpInput = ReturnType<typeof createOscorpSchema.parse>;
type AppStateEntry = { key: string; value: { type: number; uint?: number | bigint; bytes?: string } };

function readGlobalState(
  params: { "global-state"?: AppStateEntry[]; globalState?: AppStateEntry[] } | undefined,
): AppStateEntry[] {
  if (!params) return [];
  return params["global-state"] ?? params.globalState ?? [];
}

function getGlobalUint(state: AppStateEntry[], keyName: string): number | null {
  const entry = state.find((entry) => Buffer.from(entry.key, "base64").toString("utf-8") === keyName);
  if (!entry) return null;
  const value = entry.value.uint ?? 0;
  return typeof value === "bigint" ? Number(value) : value;
}

async function loadFactory() {
  // Generated by `pnpm run build` in Oscorp-contracts.
  const modulePath = "../../Oscorp-contracts/smart_contracts/artifacts/oscorp/OscorpClient";
  return (await import(modulePath)) as {
    OscorpFactory: unknown;
  };
}

export async function createOscorp(input: CreateOscorpInput) {
  const parsed = createOscorpSchema.parse(input);
  if (parsed.creatorShareBps + parsed.investorShareBps + parsed.treasuryShareBps !== 10_000) {
    throw new Error("Share bps must sum to 10000");
  }

  const algorand = getAlgorandClient();
  const deployer = await algorand.account.fromEnvironment("DEPLOYER");
  const protocolTreasury = algosdk.encodeAddress(algosdk.decodeAddress(env.PROTOCOL_TREASURY).publicKey);

  const { OscorpFactory } = await loadFactory();
  const factory = algorand.client.getTypedAppFactory(OscorpFactory as never, {
    defaultSender: deployer.addr,
  }) as {
    deploy: (args: { onSchemaBreak: "append"; onUpdate: "append" }) => Promise<{
      appClient: any;
      result: { operationPerformed: string };
    }>;
    getAppClientById: (appId: number) => Promise<any>;
  };

  const deployed = await factory.deploy({ onSchemaBreak: "append", onUpdate: "append" });
  const appClient = deployed.appClient;
  const appId = appClient.appClient.appId;
  const appAddress = algosdk.getApplicationAddress(appId);
  const appAddressString = appAddress.toString();

  // Ensure app account has enough ALGO for inner tx fees and minimum balance.
  const appInfo = await algorand.client.algod.accountInformation(appAddressString).do();
  const appBalance = Number(appInfo.amount ?? 0);
  const minRequired = 2_000_000;
  if (appBalance < minRequired) {
    await algorand.send.payment({
      sender: deployer.addr,
      receiver: appAddressString,
      amount: (2).algo(),
    });
  }

  // Idempotency: if app is already initialized, do not call createOscorp again.
  const appOnChain = await algorand.client.algod.getApplicationByID(appId).do();
  const appParams = appOnChain.params as { "global-state"?: AppStateEntry[]; globalState?: AppStateEntry[] };
  const globalState = readGlobalState(appParams);
  const initializedEntry = globalState.find(
    (entry) => Buffer.from(entry.key, "base64").toString("utf-8") === "initialized",
  );
  const initializedRaw = initializedEntry?.value?.uint ?? 0;
  const isInitialized = typeof initializedRaw === "bigint" ? initializedRaw > 0n : initializedRaw > 0;

  if (isInitialized) {
    const pulseAssetId = getGlobalUint(globalState, "pulseAsset");
    return {
      appId: typeof appId === "bigint" ? Number(appId) : appId,
      appAddress: appAddressString,
      pulseAssetId,
      createTxId: null,
      status: "already_initialized",
    };
  }

  const created = await appClient.send.createOscorp({
    args: {
      oscorpName: parsed.name,
      category: parsed.category,
      metadataUri: parsed.metadataUri,
      creator: parsed.creatorAddress,
      investor: parsed.investorAddress,
      treasury: parsed.treasuryAddress,
      protocolTreasury,
      usdcAsset: BigInt(env.USDC_ASSET_ID),
      pulseUnitName: parsed.pulseUnitName,
      pulseAssetName: parsed.pulseAssetName,
      pulseTotal: BigInt(parsed.pulseTotal),
      pulseDecimals: BigInt(parsed.pulseDecimals),
      creatorShareBps: BigInt(parsed.creatorShareBps),
      investorShareBps: BigInt(parsed.investorShareBps),
      treasuryShareBps: BigInt(parsed.treasuryShareBps),
      launchpadFeeBps: BigInt(parsed.launchpadFeeBps),
      approvalThresholdUsdc: BigInt(parsed.approvalThresholdUsdc),
      gtmBudgetUsdc: BigInt(parsed.gtmBudgetUsdc),
      minPatronPulse: BigInt(parsed.minPatronPulse),
    },
    sender: deployer.addr,
  });

  return {
    appId: typeof appId === "bigint" ? Number(appId) : appId,
    appAddress: appAddressString,
    pulseAssetId: Number(created.return ?? 0n),
    createTxId: created.transaction.txID(),
    status: "initialized",
  };
}

type UpdateOscorpPolicyInput = ReturnType<typeof updateOscorpPolicySchema.parse>;

export async function updateOscorpPolicy(input: UpdateOscorpPolicyInput) {
  const parsed = updateOscorpPolicySchema.parse(input);
  const algorand = getAlgorandClient();
  const deployer = await algorand.account.fromEnvironment("DEPLOYER");

  const { OscorpFactory } = await loadFactory();
  const factory = algorand.client.getTypedAppFactory(OscorpFactory as never, {
    defaultSender: deployer.addr,
  }) as {
    getAppClientById: (appId: number) => Promise<any>;
  };
  const appClient = await factory.getAppClientById(parsed.appId);

  const updated = await appClient.send.updatePolicy({
    args: {
      approvalThresholdUsdc: BigInt(parsed.approvalThresholdUsdc),
      gtmBudgetUsdc: BigInt(parsed.gtmBudgetUsdc),
      minPatronPulse: BigInt(parsed.minPatronPulse),
    },
    sender: deployer.addr,
  });

  return {
    appId: parsed.appId,
    txId: updated.transaction.txID(),
  };
}

function decodeAppGlobalState(state: AppStateEntry[] | undefined) {
  if (!state) return {};
  const out: Record<string, string | number> = {};
  for (const item of state) {
    const key = Buffer.from(item.key, "base64").toString("utf-8");
    if (item.value.type === 1) {
      const raw = Buffer.from(item.value.bytes ?? "", "base64");
      if (raw.length === 32) {
        // Most address/account fields are stored as raw 32-byte public keys.
        out[key] = algosdk.encodeAddress(new Uint8Array(raw));
      } else {
        out[key] = raw.toString("utf-8");
      }
    } else {
      const maybeUint = item.value.uint ?? 0;
      out[key] = typeof maybeUint === "bigint" ? Number(maybeUint) : maybeUint;
    }
  }
  return out;
}

export async function getOscorpState(appId: number) {
  const algorand = getAlgorandClient();
  const appInfo = await algorand.client.algod.getApplicationByID(appId).do();
  const params = appInfo.params as unknown as {
    creator?: string | { toString(): string };
    "global-state"?: AppStateEntry[];
    globalState?: AppStateEntry[];
  };

  return {
    appId,
    creator: params.creator ? String(params.creator) : null,
    globalState: decodeAppGlobalState(readGlobalState(params)),
  };
}
